---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: cloud-controller-manager
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstack-cloud-controller-manager
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
- apiGroups:
  - ""
  # Required by occm to annotate services
  resources:
  - services
  verbs:
  - patch
- apiGroups:
  # Required by occm to create events
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openstack-cloud-controller-manager
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  kind: ClusterRole
  name: openstack-cloud-controller-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: cloud-controller-manager
